=== aelkhodary/xml/labs/code_ex/code_05_23_n.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.hr.com/jobs"
            targetNamespace="http://www.hr.com/jobs"
            elementFormDefault="qualified" >
  <xsd:element name="jobs">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="job" maxOccurs="unbounded">
          <xsd:annotation>
            <xsd:documentation>A sample element
            </xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="job_id">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="AC_MGR"/>
                    <xsd:enumeration value="AD_PRES"/>
                    <xsd:enumeration value="FI_MGR"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="job_title" type="xsd:string"/>
              <xsd:element name="min_salary" type="xsd:string"/>
              <xsd:element name="max_salary" type="xsd:string"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== aelkhodary/xml/labs/code_ex/code_05_23_n.xml
<?xml version='1.0' encoding="UTF-8"?>
<jobs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.hr.com/jobs code_05_23_n.xsd"
      xmlns="http://www.hr.com/jobs">
  <job>
    <job_id>AC_MGR</job_id>  <!-- This ID will be valid -->
    <job_title>Account Manager</job_title>
    <min_salary>1000</min_salary>
    <max_salary>8000</max_salary>
  </job>
  <job>
    <job_id>XX_MGR</job_id>  <!-- This ID will be an error -->
    <job_title>Other Manager</job_title>
    <min_salary>1100</min_salary>
    <max_salary>75000</max_salary>
  </job>  
</jobs>
