=== aelkhodary/xml/labs/code_ex/code_05_27_s.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
  <xsd:element name="departments">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="department" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="department_id" type="xsd:int"/>
              <xsd:element name="department_name" type="xsd:string"/>
              <xsd:element name="manager_id" type="xsd:int" minOccurs="0"/>
              <xsd:element name="location_id" type="xsd:int" minOccurs="0"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== aelkhodary/xml/labs/code_ex/code_05_27_n.xml
<?xml version='1.0' encoding="UTF-8"?>
<departments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="code_05_27_s.xsd">
  <department>
    <department_id>10</department_id>
    <department_name>Administration</department_name>
  </department>
  <department>
    <department_id>20</department_id>
    <department_name>Marketing</department_name>
    <location_id>1800</location_id>
    <!-- Error -->
    <manager_id>201</manager_id>
  </department>
</departments>
