=== aelkhodary/xml/labs/code_ex/code_05_24_n.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.hr.com/jobs"
            targetNamespace="http://www.hr.com/jobs"
            elementFormDefault="qualified">
  <xsd:simpleType name="mgrTypes">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="AC_MGR"/>
      <xsd:enumeration value="FI_MGR"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="repTypes">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="AC_REP"/>
      <xsd:enumeration value="HR_REP"/>
      <xsd:enumeration value="SA_REP"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:element name="jobs">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="job" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="job_id">
                <xsd:simpleType>
                  <xsd:union memberTypes="mgrTypes repTypes"/>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="job_title"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== aelkhodary/xml/labs/code_ex/code_05_24_n.xml
<?xml version='1.0' encoding="UTF-8"?>
<jobs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.hr.com/jobs code_05_24_n.xsd"
      xmlns="http://www.hr.com/jobs">
  <job>
    <job_id>AC_MGR</job_id>  <!-- This ID will be valid -->
    <job_title>Account Manager</job_title>
  </job>
  <job>
    <job_id>AC_REP</job_id>  <!-- This ID will be valid -->
    <job_title>Other Manager</job_title>
  </job>
  <job>
    <job_id>MY_REP</job_id>  <!-- This ID will be an error -->
    <job_title>Other Manager</job_title>
  </job>  
</jobs>
