=== aelkhodary/xml/labs/code_ex/code_05_28_s.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.hr.com/employee"
            targetNamespace="http://www.hr.com/employee"
            elementFormDefault="qualified">
  <xsd:complexType name="employeeType">
    <xsd:choice>
      <xsd:element name="full_time" type="xsd:string"/>
      <xsd:element name="part_time" type="xsd:string"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:element name="employees">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="employee" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="full_name" type="xsd:string"/>
              <xsd:element name="contract" type="employeeType"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== aelkhodary/xml/labs/code_ex/code_05_28_n.xml
<?xml version='1.0' encoding="UTF-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hr.com/employee code_05_28_s.xsd"
           xmlns="http://www.hr.com/employee">
  <employee>
    <full_name>Steven King</full_name>
    <contract>
      <full_time>Permanent</full_time>
    </contract>
  </employee>
  <employee>
    <full_name>Steven King</full_name>
    <contract>
    <!-- Error can't contain both children  -->
      <full_time>Permanent</full_time>
      <part_time>Six months</part_time>
    </contract>
  </employee>
</employees>
