=== aelkhodary/xml/labs/lab/regions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="regions">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="region" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
            <xsd:element name="region_id" type="xsd:int"/>
            <xsd:element name="region_name" type="xsd:string"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== aelkhodary/xml/labs/classes/regions.xml
<?xml version='1.0' encoding="UTF-8"?>
<regions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="regions.xsd">
  <region>
    <region_id>1</region_id>
    <region_name>Europe</region_name>
  </region>
  <region>
    <region_id>2</region_id>
    <region_name>Americas</region_name>
  </region>
  <region>
    <region_id>3</region_id>
    <region_name>Asia</region_name>
  </region>
  <region>
    <region_id>4</region_id>
    <region_name>Middle East and Africa</region_name>
  </region>
</regions>
